import Store from '../redux/Store';

const colorPalette = {
  primary: '#F74B73',
  // white
  white100: '#FFFFFF',
  white200: '#FAFAFB',
  white300: '#F5F5F5',
  white400: '#F0F0F0',
  white500: '#E6E6E6', // autogenerated
  // gray
  gray100: '#D9D9DA',
  gray200: '#BFBFC0',
  gray300: '#8C8C8D',
  gray400: '#595959',
  gray500: '#424342',
  // black
  black100: '#262626',
  black200: '#1E201F',
  black300: '#141414',
  black400: '#0D0D0D',
  black500: '#000000',
};

const Colors = () => {
  const isDarkMode = Store.getState().theme;
  return {
    background: isDarkMode ? colorPalette.black300 : '#fdfdfd',
    topBackground: isDarkMode ? colorPalette.black300 : colorPalette.white100,
    border: isDarkMode ? '#444444' : '#f6f6f6',
    text: isDarkMode ? '#F4F4F4' : '#1D1D1F',
    colorTextAudio: isDarkMode ? colorPalette.white100 : '#707070',

    textBtnPrimary: isDarkMode ? '#1D1D1F' : '#F4F4F4',
    textLigth: '#A0A7B6',
    white: colorPalette.white100,
    primary: '#F74B73',
    primaryBorder: '#f96d9a',
    backgroundInputs: isDarkMode ? '#1e1f1f' : colorPalette.white300,
    btnFocusSecondary: isDarkMode
      ? colorPalette.black100
      : colorPalette.white100,
    placeholder: isDarkMode ? colorPalette.gray400 : colorPalette.gray200,
    placeholderInverted: isDarkMode
      ? colorPalette.gray200
      : colorPalette.gray400,
    drawerContent: isDarkMode ? '#1A1A1A' : colorPalette.white300,
    borderInputVariant: isDarkMode ? colorPalette.gray500 : '#eeeeee',
    borderCards: isDarkMode ? '#303130' : colorPalette.white400,
    dividerBackGround: isDarkMode ? '#212121' : '#eeeeee',
    postBackground: isDarkMode ? '#1e1f1f' : colorPalette.white400,
    newPlaceHolder: isDarkMode ? '#757575' : '#bdbdbd',
    newBackgroundInput: isDarkMode ? colorPalette.gray500 : '#eeeeee',
    error: '#E65555',
    // Nueva paleta de colores
    BackgroundPrimary: isDarkMode ? colorPalette.black500 : '#FAFAFA',
    BackgroundSecondary: isDarkMode ? '#212121' : '#FAFAFA',
    BackgroundTernary: isDarkMode ? '#121212' : '#FAFAFA',
    TitleBackGroundSecondary: isDarkMode ? colorPalette.gray100 : '#101c2c',
    TopBarPrimary: isDarkMode ? '#121212' : colorPalette.white100,

    LineDividerBackground: isDarkMode ? colorPalette.gray500 : '#EEEEEE',
    LineDividerBackgroundSpan: '#E45975',

    NotificationBackground: isDarkMode ? '#1e1f1f' : '#FFFFFF',
    NotificationIcon: isDarkMode ? '#121212' : '#E0E0E0',

    CardGroupsBorderPrimary: isDarkMode ? '#757575' : '#E0E0E0',
    CardGroupsBackground: isDarkMode ? '#212121' : colorPalette.white100,
    CardGroupsHr: isDarkMode ? colorPalette.gray500 : '#E0E0E0',
    CardGroupsButtonBackground: isDarkMode ? '#121212' : '#FAFAFA',
    CardGroupsTitle: isDarkMode ? colorPalette.white100 : colorPalette.black500,
    CardGroupsSubTitle: isDarkMode ? colorPalette.white100 : '#212121',
    PostDate: isDarkMode ? colorPalette.white100 : '#212121',
    PostTitle: isDarkMode ? '#9E9E9E' : '#212121',
    PostParagraphColor: isDarkMode ? '#757575' : '#212121',
    PostIconColor: isDarkMode ? '#FFFFFF' : '#212121',
    PostColorTop: isDarkMode ? '#171717' : '#F5F5F5',
    PostColorMain: isDarkMode ? '#1E1E1E' : '#FAFAFA',
    PostAudioBackground: isDarkMode
      ? colorPalette.black100
      : colorPalette.white100,
    PostAudioBackGroundLine: isDarkMode ? '#1E1E1E' : '#FAFAFA',
    PostAudioBackGroundButtonBackground: isDarkMode
      ? '#1E1E1E'
      : colorPalette.white300,

    colorTopTextHeader: isDarkMode
      ? colorPalette.white100
      : colorPalette.black300,
    colorIconLeftHeader: isDarkMode ? colorPalette.gray500 : '#e0e0e0',
    HeaderTitle: isDarkMode ? colorPalette.white100 : colorPalette.black300,
    HeaderBackground: isDarkMode ? '#121212' : '#FAFAFA',

    ContactItemBackground: isDarkMode ? '#1E1E1E' : colorPalette.white100,
    TextButtonTopBar: isDarkMode ? '#9E9E9E' : '#757575',
    BackgroundButtonTopBar: isDarkMode
      ? colorPalette.gray500
      : colorPalette.white300,
    TextTopBar: isDarkMode ? colorPalette.white100 : colorPalette.black300,
    TextLoader: isDarkMode ? '#EEEEEE' : '#212121',
    TextBlackWhite: isDarkMode ? colorPalette.white100 : colorPalette.black500,
    TextLabel: isDarkMode ? '#E0E0E0' : '#9E9E9E',
    TextInfoAvatar: isDarkMode ? '#797979' : '#A3A3A3',
    moreBackground: isDarkMode ? '#F04A73' : '#2457B7',
    CardBorder: isDarkMode ? colorPalette.gray500 : colorPalette.white400,
    TextInputPlaceholder: colorPalette.gray200,
    PlayBtn: isDarkMode ? colorPalette.white100 : '#E45975',
    minimumTrackTintColor: isDarkMode ? colorPalette.white100 : '#E45975',
    maximumTrackTintColor: isDarkMode ? '#1E1F1F' : '#EEEEEE',
    // TabNavigator
    TabNavigatorBackground: isDarkMode ? '#1e1f1f' : colorPalette.white100,
    TabNavigatorInactiveTintColor: isDarkMode
      ? '#6A6A6A'
      : colorPalette.gray200,
    TabNavigatorActiveTintColor: '#F04A73',

    AboutCardBackground: isDarkMode ? '#212121' : colorPalette.white300,
    TextAppnameAboutCard: isDarkMode ? '#DCDCDC' : '#757575',
    TextVersionAboutCard: isDarkMode ? '#ACACAC' : '#757575',
    TextTitleAboutCard: isDarkMode
      ? colorPalette.white100
      : colorPalette.black500,
    TextSubTitleAboutCard: isDarkMode ? '#EEEEEE' : '#212121',
    TextItemsAboutCard: isDarkMode ? '#EEEEEE' : '#212121',
    TextTermsAboutCard: isDarkMode ? '#EEEEEE' : '#212121',

    // SelectGroupType
    BackgroundCardsColorGroupType: isDarkMode ? '' : colorPalette.white100,
    BackgroundIconsColorGroupType: isDarkMode ? '#1E1F1F' : '#F04A73',
    IconsColorGroupType: isDarkMode ? '#F04A73' : colorPalette.white100,
    TextColorGroupTye: isDarkMode ? '#FCDEE5' : '#232323',
    TitleColorGroupTye: isDarkMode ? '#FCDEE5' : colorPalette.black300,

    // GroupFeedRectangle
    BackgroundRectangleColor: '#2680EB',

    CardRightRoundedBackground: isDarkMode ? '#1e1f1f' : colorPalette.white100,
    CardRightRoundedTitle: isDarkMode
      ? colorPalette.white100
      : colorPalette.black300,
    CardRightRoundedSubTitle: isDarkMode
      ? colorPalette.gray300
      : colorPalette.black300,

    CardBackground: isDarkMode ? colorPalette.black100 : colorPalette.white100,
    CardInputTitle: isDarkMode ? colorPalette.gray100 : colorPalette.black300,
    CardInputBackground: isDarkMode ? '#1e1f1f' : '#F9F9F9',
    CardInputText: isDarkMode ? '#edf0f6' : '#101c2c',

    QandATitle: isDarkMode ? colorPalette.gray400 : colorPalette.gray200,

    // CardDescription
    ColorTextCard: isDarkMode ? colorPalette.white100 : colorPalette.black300,

    backgroundPost: isDarkMode ? '#1e1f1f' : '#eeeff4',
    sildersSteps: isDarkMode ? colorPalette.gray500 : colorPalette.white100,

    audioIconColor: isDarkMode ? '#1E1F1F' : colorPalette.white100,

    // CommentsModal
    backgroundCommentsModal: isDarkMode ? '#1E1F1F' : '#f4f6f5',
    iconCommentsModal: isDarkMode ? '#C7C8C8' : '#4A4B4B',
    iconCloseModal: isDarkMode ? colorPalette.white100 : colorPalette.black300,
    textColorModal: isDarkMode ? colorPalette.white100 : '#0E0E10',
    textColorReplyTime: isDarkMode ? colorPalette.white100 : '#7D7D7F',
    textFieldBorderColor: isDarkMode ? '#1E1F1F' : '#EEEEEE',
    textFieldColor: isDarkMode ? colorPalette.black100 : colorPalette.white100,
    iconSendColor: isDarkMode ? colorPalette.black300 : colorPalette.white100,

    FilterBackgroundColor: isDarkMode ? '#424342' : '#F9F9F9',
    FilterTextColor: '#bfbfc0',
    FilterBorderColor: isDarkMode ? '#595959' : '#EEEEEE',

    HeaderIconPeople: isDarkMode ? '#424342' : '#bfbfc0',
    NewPostButtonIcon: isDarkMode ? '#F5F5F5' : '#bfbfc0',

    //GalleryPost
    inputTellLittleMore: '#f4f6f5',

    listMembersAvatar: isDarkMode ? colorPalette.gray500 : '#ECECEC',
    borderAvatar: isDarkMode ? colorPalette.white100 : colorPalette.gray200
  };
};

export default Colors;
