const Images = {
  user: require('../../assets/images/user.png'),
  groupCard: require('../../assets/images/groupCard.png'),
  logoWhite: require('../../assets/images/logoWhite100.png'),
  logo: require('../../assets/images/logo.png'),
  logoGray: require('../../assets/images/logoGray100.png'),
  logoPink: require('../../assets/images/logoPink100.png'),
  modalGroupBase: require('../../assets/images/modalGroupBase.png'),
  newGroup: require('../../assets/images/newGroup.png'),
  menuDot: require('../../assets/images/menu-dot.png'),
  notification: require('../../assets/images/nofication.png'),
  answersBackground: require('../../assets/images/answersBackground.jpg'),
  userAdd: require('../../assets/images/user-plus-regular-72.png'),
  pencil: require('../../assets/images/pencil-regular-72.png'),
  discord: require('../../assets/images/discord.png'),
  feedback: require('../../assets/images/message-add-regular-72.png'),
  reportError: require('../../assets/images/reportError.png'),
  placeHolder: require('../../assets/images/placeHolderCat.jpg'),
  share: require('../../assets/images/share.png'),
  download: require('../../assets/images/download.png'),
  logoText: require('../../assets/images/LogoText.png'),
  menu: require('../../assets/images/menu-regular-72.png'),
  placeHolderAvatar: require('../../assets/images/placeHolderAvatar.png'),
  heart: require('../../assets/images/heart.png'),
  emptyFeed: require('../../assets/images/emptyFeed.png'),
  flashOn: require('../../assets/images/flashOn.png'),
  flashOff: require('../../assets/images/flashOff.png'),
  flip: require('../../assets/images/flip.png'),
  copy: require('../../assets/images/copy.png'),
  qrLogo: require('../../assets/images/qrLogo.png'),
  group: require('../../assets/images/group.png'),
  matterText: require('../../assets/images/LogoText.png'),
  circleLogo: require('../../assets/images/circleLogo.png'),
  logoNewGroup: require('../../assets/images/logo_new_group.png'),
  logoNewGroupDark: require('../../assets/images/logo_new_group_dark.png'),
  logoLoader: require('../../assets/images/logo_loader.png'),
  logoJoin: require('../../assets/images/logo_join.png'),
  camera: require('../../assets/images/camera.png'),
  audio: require('../../assets/images/audio.png'),
  stamp: require('../../assets/images/stamp.png'),
  text: require('../../assets/images/text.png'),
  gallery: require('../../assets/images/gallery.png'),
  Tutorial01: require('../../assets/images/Tutorial01.png'),
  Tutorial02: require('../../assets/images/Tutorial02.png'),
  Tutorial03: require('../../assets/images/Tutorial03.png'),
  Tutorial04: require('../../assets/images/Tutorial04.png'),
  logoGroupAbout: require('../../assets/images/logo_group_about.png'),
  logoGroupAboutDark: require('../../assets/images/logo_group_about_dark.png'),
  playIcon: require('../../assets/images/play-icon.png'),
  logoAbout: require('../../assets/images/logo_about.png'),
  familyIcon : require('../../assets/images/icons/familyIcon.png'),
  friendsIcon : require('../../assets/images/icons/friendsIcon.png'),
  communityIcon : require('../../assets/images/icons/communityIcon.png'),
  otherIcon : require('../../assets/images/icons/otherIcon.png'),
};


export default Images;
